project:
  type: website
  output-dir: docs

website:
  title: "CANFLUX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - dataAccess.qmd
      - dataContribution.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


