project:
  type: website
  output-dir: docs

website:
  title: "CANFLUX"
  navbar:
    left:
      - index.qmd
      # - dataAccess.qmd
      # - dataContribution.qmd

format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    toc: true


babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: fr
    text: "Français"
  mainlanguage: 'en'
  languages: ['fr']
lang: en
