project:
  type: website
  output-dir: docs

website:
  title: "CanFlux"
  navbar:
    left:
      - index.qmd
      - news.qmd
      - contact.qmd
      # - dataAccess.qmd
      # - dataContribution.qmd
  sidebar:
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: history.qmd
          text: History of Canadian Flux Networks
        - href: effortsChallenges.qmd
          text: Recent Efforts and Ongoing Challenges 
        - href: dataUseExamples.qmd
          text: How can CanFlux Data be Used?
  page-footer:
    #left: |
    #  &copy; 2025 
    center: |
      &copy; 2025 &nbsp; | &nbsp; [Contact](contact.qmd) 
    #&copy; 2025 &nbsp; [About Us](about.qmd) | [Contact](about.qmd) 
    #right: |
    #  [About Us](about.qmd) | [Contact](contact.qmd)
          
format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    toc: true


babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: fr
    text: "Français"
  mainlanguage: 'en'
  languages: ['fr']
lang: en
