---
title: "History of Canadian Flux Networks"
---

***

Despite decades of scientific leadership, beginning with the pioneering [BOREAS](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/97JD03300){target="_blank"} experiment in the 1990s, continuing with [BERMS](https://water.usask.ca/berms/index.php){target="_blank"} in 1997, then [Fluxnet-Canada](https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-fluxnet-canada-1335-1){target="_blank"}, and more recently the [Canadian Carbon Program](https://www.sciencedirect.com/science/article/abs/pii/S0168192312002109){target="_blank"}, Canada’s ecosystem–atmosphere monitoring capacity remains fragmented.

BOREAS and Fluxnet-Canada were concentrated largely south of 60°N, reflecting the technological limitations of the time; earlier instruments required high power, intensive maintenance, and year-round staffing that [made Arctic deployment impractical](https://bg.copernicus.org/articles/9/3185/2012/){target="_blank"}. Recent advances in low-power, low-maintenance sensors now make long-term flux measurements feasible in remote and northern environments, opening the possibility of monitoring previously inaccessible regions that are among the most climate-sensitive in Canada.

<!-- These foundational programs established national benchmarks for flux science, produced long-term datasets that transformed understanding of temperate and boreal carbon and water cycling, and built a connected community of climate scientists, modellers, and technicians. -->

These programs established national benchmarks for flux science, produced long-term datasets that transformed understanding of temperate and boreal carbon and water cycling, and built a connected community of climate scientists, modellers, and technicians, providing a strong foundation for CanFlux.