---
title: "Histoire des réseaux de flux canadiens"
---

***

Malgré des décennies de leadership scientifique, à commencer par l’expérience pionnière [BOREAS](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/97JD03300){target="_blank"} dans les années 1990, poursuivie avec [BERMS](https://water.usask.ca/berms/index.php){target="_blank"} en 1997, puis [Fluxnet-Canada](https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-fluxnet-canada-1335-1){target="_blank"}et plus récemment le [Programme canadien du carbone](https://www.sciencedirect.com/science/article/abs/pii/S0168192312002109){target="_blank"}, la capacité de surveillance des écosystèmes et de l’atmosphère du Canada demeure fragmentée.

BOREAS et Fluxnet-Canada étaient concentrés en grande partie au sud du 60e parallèle nord, reflétant les limitations technologiques de l'époque ; les instruments plus anciens nécessitaient une puissance élevée, un entretien intensif et un personnel à l'année, ce qui [rendait le déploiement dans l'Arctique impraticable](https://bg.copernicus.org/articles/9/3185/2012/){target="_blank"}. Grâce aux progrès récents réalisés dans le domaine des capteurs à faible consommation et nécessitant peu d'entretien, il est désormais possible d'effectuer des mesures de flux à long terme dans des environnements éloignés et nordiques, ce qui ouvre la possibilité de surveiller des régions auparavant inaccessibles qui figurent parmi les plus sensibles au climat au Canada.

Ces programmes ont établi des normes nationales pour la science des flux, produit des ensembles de données à long terme qui ont transformé la compréhension du cycle du carbone et de l'eau dans les régions tempérées et boréales, et construit une communauté connectée de climatologues, de modélisateurs et de techniciens, fournissant une base solide à CanFlux.