---
title: "Home"
template-partials:
  - title-block.html
toc: false
---

# CanFlux: Coordinated Observations of Ecosystem–Climate Interactions Across Canada

Canadian ecosystems play a vital role in regulating the climate by exchanging CO₂, de CH₄ et de N₂O across natural and managed forests, wetlands, croplands, and grasslands. While Canada has a strong legacy of eddy covariance flux measurements, national coordination has waned since the end of <a href="https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-fluxnet-canada-1335-1" target="_blank">FLUXNET Canada in 2014<a>. As a result, valuable datasets remain underutilized due to fragmented infrastructure and limited long-term support - hindering efforts to track greenhouse gas (GHG) fluxes and advance Indigenous-led stewardship, nature-based climate solutions, carbon markets, and climate policy. 

CanFlux is a revitalized national network dedicated to measuring and understanding carbon, water, and energy exchanges between Canada’s ecosystems and the atmosphere. By integrating flux tower measurements, ground observations, remote sensing, and modelling, CanFlux will provide the data and tools needed to track ecosystem responses to climate change, improve predictive models, and guide risk mitigation and sustainable management decisions. Rooted in collaboration among scientists, governments, Indigenous partners, NGOs, and the private sector, CanFlux strengthens Canada’s capacity to anticipate and adapt to climate-related risks while advancing its climate goals through open, high-quality, and policy-relevant environmental observations. 

