---
title: "Accueil"
template-partials:
  - title-block.html
toc: false
---

# CanFlux: Observations coordonnées des interactions écosystème-climat au Canada

Les écosystèmes canadiens jouent un rôle essentiel dans la régulation du climat par les échanges de CO₂, de CH₄ et de N₂O entre les forêts naturelles et aménagées, les milieux humides, les terres cultivées et les prairies. Bien que le Canada possède un solide héritage de mesures des flux de covariance des turbulences, la coordination nationale s'est affaiblie depuis la fin de <a href="https://www.earthdata.nasa.gov/data/catalog/ornl-cloud-fluxnet-canada-1335-1" target="_blank">FLUXNET Canada en 2014<a>. Par conséquent, de précieux ensembles de données demeurent sous-utilisés en raison d'une infrastructure fragmentée et d'un soutien à long terme limité, ce qui entrave les efforts de suivi des flux de gaz à effet de serre (GES) et de promotion de l'intendance autochtone, des solutions climatiques fondées sur la nature, des marchés du carbone et des politiques climatiques.

CanFlux est un réseau national revitalisé dédié à la mesure et à la compréhension des échanges de carbone, d'eau et d'énergie entre les écosystèmes canadiens et l'atmosphère. En intégrant les mesures des tours de flux, les observations au sol, la télédétection et la modélisation, CanFlux fournira les données et les outils nécessaires pour suivre les réponses des écosystèmes aux changements climatiques, améliorer les modèles prédictifs et orienter les décisions en matière d'atténuation des risques et de gestion durable. Fondé sur la collaboration entre scientifiques, gouvernements, partenaires autochtones, ONG et le secteur privé, CanFlux renforce la capacité du Canada à anticiper et à s’adapter aux risques liés au climat tout en faisant progresser ses objectifs climatiques grâce à des observations environnementales ouvertes, de haute qualité et pertinentes pour les politiques.


